### ISSUE TITLE
Syntax adjustment

### ISSUE THREAD

**Issue by tfdahlin** [DaylightingSociety/Paillier#4]
[This](https://github.com/DaylightingSociety/Paillier/blob/master/lib/paillier/zkp.rb#L237) can be changed to the form `<array>.join(',')` to read more clearly.

**Comment by milo-trujillo** [comment]
Perhaps we thought the old syntax was necessary to ensure a cast to string, but lists of integers and lists of OpenSSL BigNums will both auto-cast to strings if you call .join() on them, so this change looks great.

**Comment by tfdahlin** [comment]
This was also basically my first real ruby project, and one of my first programming projects in general, so I wasn't a great coder at the time :p I suspect that's more of the reason than anything.

**Comment by tfdahlin** [comment]
Another minor adjustment:
https://github.com/DaylightingSociety/Paillier/blob/master/lib/paillier/zkp.rb#L61

I believe this can be replaced with `valid_messages.each do {...}`

**Comment by milo-trujillo** [comment]
Agreed. I think the syntax would be:

```ruby
valid_messages.each do |m_k|
    # Contents of the block
end
```
